### ISSUE TITLE
关于增加tabs覆盖l-tabs-header的外部类

### ISSUE THREAD

**Issue by KuoKongQingYun** [TaleLin/lin-ui#1091]
默认的.l-tabs-header是纯白背景，我想覆盖这个背景，测试过l-header-class，但发现这个是上级标签的class，无法覆盖.l-tabs-header的背景

**Comment by murongg** [comment]
试一下 
```css
.l-header-class .l-tabs-header {
  background: red !important;
}
```
