### ISSUE TITLE
image-picker组件样式bug

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#557]
**LinUI版本（必填）：**
0.6.7
**设备（必填）：**
iphone11promax
**基础库版本（必填）：**

**UI问题，请附上截图**
当上传图片少于3张时，picker直接没有边距，当上传图片大于3张时，picker有边距，请及时处理，谢谢，急需用
**重现步骤，必要时请提供代码片段链接**
``` WXML
 <l-image-picker l-class="imagePicker" name="pic" size="3"  custom="{{true}}">
                <view class="camera">
                    <image class="add-icon" src="/images/camera_add.png" />
                    <text class="add-text">选择图片</text>
                </view>
  </l-image-picker>
```
``` less
.camera{
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    .add-icon{
        height: 70rpx;
        width: 70rpx;
        margin-top: 10rpx;
    }
    .add-text {
        margin-top: 6rpx;
        font-size: 22rpx;
        color: #999;
    }
}
```
