### ISSUE TITLE
input组件设置placeholder-style无效

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#630]
**LinUI版本（必填）：**
0.6.12
**设备（必填）：**
模拟器
**基础库版本（必填）：**
最新
**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
```html
<l-input
        l-class="search-input-l-class"
        focus="{{true}}"
        clear="{{true}}"
        width="514"
        hideLabel="true"
        placeholder="输入姓名或学号"
        placeholder-style="search-input-placeholder"
/>
```

```css
.search-input-placeholder{
  color: aqua !important;
  font-size: 282rpx !important;
}
```

这样设置没有效果
