### ISSUE TITLE
l-tabs 组件在 iphone6 Plus 真机存在切换 tab 内容闪现问题

### ISSUE THREAD

**Issue by YYJeffrey** [TaleLin/lin-ui#729]
**LinUI版本 0.7.5 ：**

**设备 iphone6 Plus ：**

**基础库版本 2.10.3 ：**

问题：在模拟器运行以下代码一切正常，当在真机iPhone6P环境下运行或其他iPhone设备下运行会出现切换tab时除第一个tab其他tab内容一闪而过的问题。

```WXML
<l-tabs bind:linchange="changeTabs">
	<l-tabpanel tab="京东物流" key="one" slot="one">
		<view class="tab-content">京东物流</view>
	</l-tabpanel>
	<l-tabpanel tab="品牌" key="two" slot="two">
		<view class="tab-content">品牌</view>
	</l-tabpanel>
	<l-tabpanel tab="接口" key="three" slot="three">
		<view class="tab-content">接口</view>
	</l-tabpanel>
	<l-tabpanel tab="面板" key="four" slot="four">
		<view class="tab-content">面板</view>
	</l-tabpanel>
</l-tabs>
```

解决办法：注释掉 l-tabs 样式中的以下两行代码。

```CSS
.l-tabpanel {
  width: 100%;
  height: 100%;
  -webkit-flex-shrink: 0;
  -ms-flex-negative: 0;
  flex-shrink: 0;
  /* -webkit-transition: opacity .45s;
  transition: opacity .45s; */
  opacity: 1;
  text-overflow: ellipsis
}
```
