### ISSUE TITLE
求解：混合标签 Combined Tabs 在使用的时候，内容区域出不来，为什么？该怎么做？

### ISSUE THREAD

**Issue by gavinchenz** [TaleLin/lin-ui#917]
**LinUI版本（必填）：**
0.8.3
**设备（必填）：**
小程序开发工具
**基础库版本（必填）：**
2.11.1
**UI问题，请附上截图**
**问题描述：根据业务开发需求，因为要区分大分类和子分类，因此准备用Combined Tabs 做一个商品的列表页，第一次使用LinUI 来开发小程序，遇到了问题，在这里说一下，希望能有人帮忙解决，先谢了。问题：混合标签 Combined Tabs 在使用的时候，内容区域出不来，为什么？该怎么做？**
**goodsList.wxml:**
```html
<!-- goodsList.wxml -->
<l-combined-tabs bind:linchange="changeTabs" scrollable="{{true}}" active-key='one' animated="{{false}}" active-color='#cf4523' inactive-color='#405f80' l-content-class='l-content-class'>
	<block wx:for="{{classificationList}}" wx:key='index'>
		<l-tabpanel tab="{{item.tab}}" key="{{item.key}}" slot="{{item.key}}" sub-tab='{{item.subTab}}' sub-key='{{item.subKey}}'>
			<view class="tab-content">{{item.tab}}</view>
		</l-tabpanel>
	</block>
</l-combined-tabs>
```

**goodsList.json：**
```json
//goodsList.json
{
  "usingComponents": {
    "l-toast": "/miniprogram_npm/lin-ui/toast/index",
    "l-combined-tabs": "/miniprogram_npm/lin-ui/combined-tabs/index",
    "l-tabs": "/miniprogram_npm/lin-ui/tabs/index",
    "l-tabpanel": "/miniprogram_npm/lin-ui/tabpanel/index"
  }
}
```
**goodsList.wxss:**
```css
/*goodsList.wxss */
.l-content-class{
  width:300rpx;
  height:300rpx;
  background: #405f80;
  color:#fff;
}
.tab-content{
  width:500rpx;
  height:400rpx;
  background: #ac0;
  color:purple;
}
````
**这个tab-content的view出不来，用插值绑定的 item.tab 也不显示，请问为什么，这个问题出在哪里？应该如何修改？**
